import {radians, rndInt} from "./utils";
import Physics from "PhysicsJS";

export default class Asteroid {

    //x, y - start coordinates
    constructor(x, y, radius, mass=1) {
        let vertices = [],
            angle = 0;

        this.radius = radius;

        //asteroid is generated by adding vertices at random angles
        while (angle < 360) {
            let vec = new Physics.vector(this.radius, 0);
            vec.rotate(new Physics.transform(null, radians(angle), new Physics.vector(0, 0)));
            vertices.push(vec);
            angle += rndInt(20, 70);
        }

        this.body = Physics.body('convex-polygon', {
            x,
            y,
            vertices,
            mass: mass,
            restitution: 1
        });
    }
    
}